/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversityRouteImport } from './routes/$university'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AttendanceCalculatorRouteImport } from './routes/attendance-calculator'
import { Route as CgpaCalculatorRouteImport } from './routes/cgpa-calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GpaConverterRouteImport } from './routes/gpa-converter'
import { Route as PercentageCalculatorRouteImport } from './routes/percentage-calculator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SgpaCalculatorRouteImport } from './routes/sgpa-calculator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as UniversityIndexRouteImport } from './routes/$university.index'
import { Route as UniversityToolRouteImport } from './routes/$university.$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityRoute = UniversityRouteImport.update({
  id: '/$university',
  path: '/$university',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceCalculatorRoute = AttendanceCalculatorRouteImport.update({
  id: '/attendance-calculator',
  path: '/attendance-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CgpaCalculatorRoute = CgpaCalculatorRouteImport.update({
  id: '/cgpa-calculator',
  path: '/cgpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaConverterRoute = GpaConverterRouteImport.update({
  id: '/gpa-converter',
  path: '/gpa-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentageCalculatorRoute = PercentageCalculatorRouteImport.update({
  id: '/percentage-calculator',
  path: '/percentage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SgpaCalculatorRoute = SgpaCalculatorRouteImport.update({
  id: '/sgpa-calculator',
  path: '/sgpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityIndexRoute = UniversityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityToolRoute = UniversityToolRouteImport.update({
  id: '/$tool',
  path: '/$tool',
  getParentRoute: () => UniversityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$university': typeof UniversityRouteWithChildren
  '/about': typeof AboutRoute
  '/attendance-calculator': typeof AttendanceCalculatorRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/gpa-converter': typeof GpaConverterRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/sgpa-calculator': typeof SgpaCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/universities': typeof UniversitiesRoute
  '/$university/$tool': typeof UniversityToolRoute
  '/$university/': typeof UniversityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance-calculator': typeof AttendanceCalculatorRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/gpa-converter': typeof GpaConverterRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/sgpa-calculator': typeof SgpaCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/universities': typeof UniversitiesRoute
  '/$university/$tool': typeof UniversityToolRoute
  '/$university': typeof UniversityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$university': typeof UniversityRouteWithChildren
  '/about': typeof AboutRoute
  '/attendance-calculator': typeof AttendanceCalculatorRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/gpa-converter': typeof GpaConverterRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/sgpa-calculator': typeof SgpaCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/universities': typeof UniversitiesRoute
  '/$university/$tool': typeof UniversityToolRoute
  '/$university/': typeof UniversityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$university'
    | '/about'
    | '/attendance-calculator'
    | '/cgpa-calculator'
    | '/contact'
    | '/gpa-converter'
    | '/percentage-calculator'
    | '/privacy'
    | '/sgpa-calculator'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/universities'
    | '/$university/$tool'
    | '/$university/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attendance-calculator'
    | '/cgpa-calculator'
    | '/contact'
    | '/gpa-converter'
    | '/percentage-calculator'
    | '/privacy'
    | '/sgpa-calculator'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/universities'
    | '/$university/$tool'
    | '/$university'
  id:
    | '__root__'
    | '/'
    | '/$university'
    | '/about'
    | '/attendance-calculator'
    | '/cgpa-calculator'
    | '/contact'
    | '/gpa-converter'
    | '/percentage-calculator'
    | '/privacy'
    | '/sgpa-calculator'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/universities'
    | '/$university/$tool'
    | '/$university/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UniversityRoute: typeof UniversityRouteWithChildren
  AboutRoute: typeof AboutRoute
  AttendanceCalculatorRoute: typeof AttendanceCalculatorRoute
  CgpaCalculatorRoute: typeof CgpaCalculatorRoute
  ContactRoute: typeof ContactRoute
  GpaConverterRoute: typeof GpaConverterRoute
  PercentageCalculatorRoute: typeof PercentageCalculatorRoute
  PrivacyRoute: typeof PrivacyRoute
  SgpaCalculatorRoute: typeof SgpaCalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$university': {
      id: '/$university'
      path: '/$university'
      fullPath: '/$university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-calculator': {
      id: '/attendance-calculator'
      path: '/attendance-calculator'
      fullPath: '/attendance-calculator'
      preLoaderRoute: typeof AttendanceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgpa-calculator': {
      id: '/cgpa-calculator'
      path: '/cgpa-calculator'
      fullPath: '/cgpa-calculator'
      preLoaderRoute: typeof CgpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-converter': {
      id: '/gpa-converter'
      path: '/gpa-converter'
      fullPath: '/gpa-converter'
      preLoaderRoute: typeof GpaConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentage-calculator': {
      id: '/percentage-calculator'
      path: '/percentage-calculator'
      fullPath: '/percentage-calculator'
      preLoaderRoute: typeof PercentageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgpa-calculator': {
      id: '/sgpa-calculator'
      path: '/sgpa-calculator'
      fullPath: '/sgpa-calculator'
      preLoaderRoute: typeof SgpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$university/': {
      id: '/$university/'
      path: '/'
      fullPath: '/$university/'
      preLoaderRoute: typeof UniversityIndexRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/$university/$tool': {
      id: '/$university/$tool'
      path: '/$tool'
      fullPath: '/$university/$tool'
      preLoaderRoute: typeof UniversityToolRouteImport
      parentRoute: typeof UniversityRoute
    }
  }
}

interface UniversityRouteChildren {
  UniversityToolRoute: typeof UniversityToolRoute
  UniversityIndexRoute: typeof UniversityIndexRoute
}

const UniversityRouteChildren: UniversityRouteChildren = {
  UniversityToolRoute: UniversityToolRoute,
  UniversityIndexRoute: UniversityIndexRoute,
}

const UniversityRouteWithChildren = UniversityRoute._addFileChildren(
  UniversityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UniversityRoute: UniversityRouteWithChildren,
  AboutRoute: AboutRoute,
  AttendanceCalculatorRoute: AttendanceCalculatorRoute,
  CgpaCalculatorRoute: CgpaCalculatorRoute,
  ContactRoute: ContactRoute,
  GpaConverterRoute: GpaConverterRoute,
  PercentageCalculatorRoute: PercentageCalculatorRoute,
  PrivacyRoute: PrivacyRoute,
  SgpaCalculatorRoute: SgpaCalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
